### PR TITLE
Added support for the recent FIRMs (> 9.0.0) + Fix N3DS clock patch + Added Friends module, ErrDisp, DLP region patch

### PR DESCRIPTION
**Pull request by GrayJack**
And there was a weird behaviour with stuff that I didn't change but git said that I deleted and added the same thing.

### CODE REVIEW

**Comment by Wolfvak** [comment]
I'm not really sure it's a good idea to add support for old FIRMs, since it's an open source reimplementation. Have you tested 4.x FIRM with this patch?

**Comment by GrayJack** [comment]
I have no way to test it right now, but I can remove the old FIRMs, maybe letting only from 9.0.0 till the latest?

I have in my local repository friends module, errdisp and dlp region patch if you are interested with it

**Comment by Wolfvak** [comment]
Yeah, both points would be highly appreciated.

 GrayJack <notifications@github.com> wrote:



I have no way to test it right now, but I can remove the old FIRMs, maybe letting only from 9.0.0 till the latest?

I have in my local repository friends module, errdisp and dlp region patch if you are interested with it

**Comment by GrayJack** [comment]
So I'll remove the FIRMs before 9.0.0 that I added, and let the ones that was already implemented, cause I'm assuming that these ones was already tested

**Pull request merged**
